apiVersion: v2
description: Toolkit for building data processing pipelines.
name: spring-cloud-data-flow
version: 2.6.1
appVersion: 2.4.0.RELEASE
type: application
home: http://cloud.spring.io/spring-cloud-dataflow/
sources:
- https://github.com/spring-cloud/spring-cloud-dataflow
- https://github.com/spring-cloud/spring-cloud-skipper
icon: https://raw.githubusercontent.com/spring-io/dataflow.spring.io/master/src/images/dataflow-icon.png
maintainers:
- name: trisberg
  email: trisberg@pivotal.io
- name: chrisjs
  email: cschaefer@vmware.com
- name: sabbyanandan
  email: sanandan@pivotal.io
dependencies:
- name:  mysql
  version: 1.6.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: mysql.enabled
- name:  rabbitmq
  version: 6.16.6
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq.enabled
- name:  rabbitmq-ha
  version: 1.38.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: rabbitmq-ha.enabled
- name:  kafka
  version: 0.20.8
  repository: https://kubernetes-charts-incubator.storage.googleapis.com/
  condition: kafka.enabled
- name: prometheus
  version: 10.4.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: features.monitoring.enabled
- name: grafana
  version: 4.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: features.monitoring.enabled
